### 잔액 충전 API
POST http://localhost:8080/api/v1/balances
Content-Type: application/json

{
  "userId": 12345,
  "amount": 10000
}

### 잔액 조회 API
GET http://localhost:8080/api/v1/balances/users/12345
Content-Type: application/json
