### 장바구니 상품 추가 API
POST http://localhost:8080/api/v1/carts
Content-Type: application/json

{
  "userId": 12345,
  "productId": 1,
  "quantity": 2
}

### 장바구니 상품 삭제 API
DELETE http://localhost:8080/api/v1/carts/users/12345/products/2
Content-Type: application/json

### 장바구니 조회 API
GET http://localhost:8080/api/v1/carts/users/12345
Content-Type: application/json
