name: master CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 브랜치 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # gradle 실행 권한 허용
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew

      # JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle build
      - name: Build with gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build

      # Docker build & push
      # GITHUB_SHA : GitHub 커밋 앞 7자리
      - name: Build and Push Docker image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t ecommerce .
          docker tag ecommerce ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:${GITHUB_SHA::7}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ecommerce:${GITHUB_SHA::7}
